[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm cache clean --force', 'npm install --production=false']

[phases.build]
cmds = ['npm run build']

# Static site deployment - no start phase needed